name: DryRunGenPR
on:
  pull_request:
  workflow_dispatch:
jobs:
  dryrun-gen:
    if: github.repository == 'aws/karpenter-provider-aws'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - run: make prepare-website
        env:
          GIT_TAG: v0.10000.0 # Mock version for testing website generation
